services:

    web:
        image: nginx:latest
        working_dir: /app
        volumes:
            - ./:/app
            - ./.docker/web/rootfs/etc/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${APP_PORT:-80}:80
        links:
            - app

    app:
        build:
            context: .docker/app
        command: php-fpm -F -R
        expose:
            - 9000
            - 9003
            - 9222
        depends_on:
            - mysql
        volumes:
            - ./:/app:delegated
            - ./.docker/app/rootfs/usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:delegated
            - ./.docker/app/rootfs/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
            - ./.docker/app/rootfs/usr/local/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#            - ./.docker/app/composer/auth.json:/var/www/.cache/composer/auth.json
            - composer:/var/www/.cache
        environment:
            APP_DEBUG: 1
            APP_ENV: dev
            DATABASE_URL: mysql://root:mysql@mysql/sylius_%kernel.environment%?serverVersion=8.0&charset=utf8mb4
            PHP_DATE_TIMEZONE: Europe/Warsaw
            PHP_IDE_CONFIG: serverName=sylius
            MAILER_DSN: smtp://mailhog:1025
            NPM_CONFIG_PATH: /var/www/.npm

    node:
        image: node:18-alpine
        working_dir: /app/tests/Application
        volumes:
            - ./:/app
        command: sh -c "yarn install --pure-lockfile; yarn watch"

    mysql:
        image: mysql:8.0
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306

    mailhog:
        image: mailhog/mailhog
        ports:
            - "${MAILHOG_PORT:-8025}:8025" # UI
            - "1025:1025"

volumes:
    composer: ~
