# Delete these routes and define your own shop routes here

hubertinio_sylius_key_value_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Hubertinio\SyliusKeyValuePlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

hubertinio_sylius_key_value_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Hubertinio\SyliusKeyValuePlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
