sylius_resource:
  resources:
    hubertinio_sylius_key_value_plugin.key_value:
      driver: doctrine/orm
      classes:
        model: Hubertinio\SyliusKeyValuePlugin\Entity\KeyValue
        interface: Hubertinio\SyliusKeyValuePlugin\Entity\KeyValueInterface
        form: Sylius\Bundle\ResourceBundle\Form\Type\DefaultResourceType
        repository: Hubertinio\SyliusKeyValuePlugin\Repository\KeyValueRepository
        controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
        factory: Sylius\Component\Resource\Factory\Factory
